# Security Configuration
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://test-auth.example.com
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=https://test-auth.example.com/.well-known/jwks.json

# Salesforce Configuration
salesforce.base-url=https://test.salesforce.com/services/data/v53.0
salesforce.client-id=test-client-id
salesforce.client-secret=test-client-secret
salesforce.username=test@example.com
salesforce.password=test-password
salesforce.security-token=test-token
salesforce.opportunityPricebookId=test-pricebook-id
